name: Test

on:
  push:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        npm i --dev
        npm run build
    - name: Test
      run: |
        mkdir -p evermizer.js/v000
        phpunit tests #--display-deprecations

  trigger_publish_preview:
    if: github.event_name == 'push' && github.ref_name == 'main'

    runs-on: ubuntu-latest
    needs:
      - unit-test

    steps:
    - name: Trigger workflow run
      env:
        GH_TOKEN: ${{ secrets.EVERMIZER_PAT }}
      if: ${{ env.GH_TOKEN != '' }}
      run: |
        repo="${{ github.repository_owner }}/evermizer"
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$repo/dispatches \
            -f "event_type=wasm-ui-update"
